HBClab/RestingState

dataPrep.sh
qualityCheck.sh
variable_dictionary.txt

changes in qualityCheck, started putting lines of code into functions.
made some logging more efficient in dataPrep.sh

WIP: qualityCheck.sh

---

processRestingState_bids_wrapper.sh

Rather than specifying the output directory, script now has -i flag to specify the input file to be processed by wrapper script. 
JK EDIT:
Addresses #25

changed cmd opts. use -i flag for input file rather than -o flag for rsOut

---

processRestingState_bids_wrapper.sh

Fixed path on line 112

---

makeROI_Noise.sh

[STY] shellcheck and pep8 conform makeROI_Noise.sh

---

makeROI_batch.sh

[STY] shellcheck and pep8 conform for makeROI_batch.sh

---

processRestingState_bids_wrapper.sh

[STY]: shellcheck and pep8 conform processRestingState_bids_wrapper.sh

---

qualityCheck.sh

[STY] shellcheck and pep8 conform qualityCheck.sh

---

removeNuisanceRegressor.sh

[STY] shellcheck and pep8 conform removeNuisanceRegressor.sh

---

reproc_2016.sh

[STY] shellcheck and pep8 conform reproc_2016.sh

---

sd.sh

[STY] shellcheck and pep8 conform sd.sh

---

seedVoxelCorrelation_no_mapping.sh

[STY] shellcheck and pep8 conform seedVoxelCorrelation_no_mapping.sh

---

seedVoxelCorrelation.sh

[STY] shellcheck and pep8 conform seedVoxelCorrelation.sh

---

.travis.yml

- initialize automatic testing with travisci

[WIP,ENH] adding shellcheck travisci

---

restingStatePreprocess.sh

[STY] shellcheck and pep8 conform restingStatePreprocess.sh

---

removeNuisanceRegressor.sh

- Makes removeNuisanceRegressor.sh conform to shellcheck

[WIP,STY] shellcheck removeNuisanceRegressor.sh

---

tests/shellcheck.sh

- Set conditional so travisci will test correctly on first and subsequent commits

 [FIX] make the test run correctly on the first commit

---

removeNuisanceRegressor.sh

Fixes #60 
- removed backslash in inappropriate location

[FIX] syntax error creating nuisance.fsf

---

.dockerignore
Dockerfile

Helps with  #62 
- adds dockerfile for building identical development environments in docker

[ENH] add dockerfile

---

dummy_nuisance_compcor_5.0.10.fsf
dummy_nuisance_compcor_regFix_5.0.10.fsf

dummy fsf's for compcor nuisance regression were missing.

[FIX] added dummy fsfs for compcor nuisance reg.

---

dummy_nuisance_compcor_nofmap_5.0.10.fsf
dummy_nuisance_compcor_nofmap_regFix_5.0.10.fsf
dummy_nuisance_no_fmap_regFix_5.0.10.fsf
dummy_nuisance_nofmap_5.0.10.fsf
proc_fmap.sh
removeNuisanceRegressor.sh
reproc_nofmap.sh
seedVoxelCorrelation.sh

[STY] 
- Remove unused variables from seedVoxelCorrelation.sh

[STY] seed voxel correlation.sh

---

dummy_nuisance_compcor_nofmap_5.0.10.fsf
dummy_nuisance_compcor_nofmap_regFix_5.0.10.fsf
dummy_nuisance_no_fmap_regFix_5.0.10.fsf
dummy_nuisance_nofmap_5.0.10.fsf
proc_fmap.sh
qualityCheck.sh
removeNuisanceRegressor.sh
reproc_nofmap.sh
seedVoxelCorrelation.sh

Changes proposed in this pull request:
- Make a function for motion correction

[STY] Motion correction function in qualityCheck.sh

---

qualityCheck.sh
restingStatePreprocess.sh

[ENH, REF] refactor 
- Change arg parsing
- add median scaling for ICA-AROMA
- rain functions
- use clobber function instead of if-then. 
WIP: add flag for different reg options?
Note: This PR contains duplicate commits from PR #71 because I didn't `git checkout master` before creating this new branch :grimacing:.
```
~/Documents/git/RestingState/restingStatePreprocess.sh --epi=/Users/tbweng/vosslabhpc/Projects/Bike_ATrain/Imaging/BIDS/derivatives/test/sub-GEA161_ses-activepre/RestingState.nii.gz \
--t1brain=/Users/tbweng/vosslabhpc/Projects/Bike_ATrain/Imaging/BIDS/derivatives/MBA/sub-GEA161/ses-activepre/sub-GEA161_ses-activepre_T1w_brain.nii.gz \
--tr=2 \
--te=30 \
--s=6 \
--aroma \
-f -c
```

[ENH, REF] Refactor restingStatePreprocess.sh

---

motionScrub.sh
motionscrub.m

Changes proposed:
- adapt motion scrubbing scripts to accept residual data from nuisance regression using 3dTproject
- print out text files of fd and dvars along with plots

[FIX, ENH] motionScrub.sh

---

seedVoxelCorrelation.sh

- organize output of seedVoxelCorrelation.sh
- separate data processed with classic vs compcor

[ENH] organize output of seedVoxelCorrelation.sh

---

removeNuisanceRegressor.sh

- squash shellcheck warnings
- change outDir to /nuisanceRegression

[WIP, STY, ENH] removeNuisanceRegressors.sh

---

processRestingState_bids_wrapper.sh

Fixes # 91
-wrapper only looks for fieldmaps if they are flagged to be integrated with analysis

FIX: fix obligitory check for fmap

---

.circleci/config.yml
Dockerfile
processRestingState_bids_wrapper.sh

Fixes #101
- remove the freesurfer installation and environment variables from the Dockerfile

[MAINT] remove freesurfer from Dockerfile
